name: flutter_application_amal
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^5.0.2
  flutter_map: ^6.1.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  iconsax: ^0.0.8
  primer_progress_bar: ^0.4.1
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:

  
 uses-material-design: true

  